services:
  - type: web
    name: crunchybot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: REQUIRED_CHANNELS
        sync: false
      - key: HEALTH_PORT
        value: "8080"
    healthCheckPath: /health
